server:
  port: 8761

spring:
  application:
    name: eureka-discovery-server
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false