spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd

  sql:
    init:
      #      mode: never
      mode: always
  #      data-locations: data.sql
  #      schema-locations: schema.sql

  jpa:
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework:
        security: DEBUG