spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/hw11

  shell:
    interactive:
      enabled: true
  #    main:
  #      allow-circular-references: true

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.db.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    root: ERROR
