server:
  port: 8081

spring:
  application:
    name: client-service
  profiles:
    active: resilience4j
  cloud:
    config:
      enabled: false
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG