spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    open-in-view: false
    generate-ddl: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  #        enable_lazy_load_no_trans: true

  sql:
    init:
      mode: always

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true

  thymeleaf:
    cache: false