version: '3'
services:
  hw17-app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    image: hw17-app:1.0
    container_name: hw17-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/demoDB
      SPRING_DATASOURCE_USERNAME: usr
      SPRING_DATASOURCE_PASSWORD: pwd

  postgres:
    image: "postgres:13"
    container_name: postgres
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: demoDB